#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_5x15(
			KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_MINS, KC_GRV,  KC_EQL,  KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
			KC_TAB,  KC_Q,    KC_W,    KC_F,    KC_P,    KC_B,    KC_LBRC, KC_NUBS, KC_RBRC, KC_J,    KC_L,    KC_U,    KC_Y,    KC_SCLN, KC_BSPC,
			KC_LCTL, KC_A,    KC_R,    KC_S,    KC_T,    KC_G,    KC_HOME, KC_NUHS, KC_PGUP, KC_M,    KC_N,    KC_E,    KC_I,    KC_O,    KC_QUOT,
			KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_D,    KC_V,    KC_END,  KC_UP,   KC_PGDN, KC_K,    KC_H,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
			KC_ESC,  KC_LCTL, KC_LGUI, KC_LALT, MO(3),   KC_SPC,  KC_LEFT, KC_DOWN, KC_RGHT, KC_SPC,  MO(2),   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT),
	[1] = LAYOUT_ortho_5x15(
			KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_NLCK, KC_PSLS, KC_PAST, KC_BSPC,
			KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_INS,  KC_HOME, KC_PGUP, KC_P7,   KC_P8,   KC_P9,   KC_PMNS,
			KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_DEL,  KC_END,  KC_PGDN, KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
			KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_NO,   KC_UP,   KC_NO,   KC_P1,   KC_P2,   KC_P3,   KC_TRNS,
			KC_LCTL, KC_LGUI, KC_LALT, MO(3),   KC_SPC,  KC_SPC,  KC_SPC,  KC_SPC,  KC_LEFT, KC_DOWN, KC_RGHT, KC_P0,   KC_P0,   KC_PDOT, KC_PENT),
	[2] = LAYOUT_ortho_5x15(
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
			KC_TRNS, KC_PERC, KC_AT,   KC_NUHS, KC_PLUS, KC_EXLM, KC_LCBR, KC_TRNS, KC_RCBR, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_TRNS,
			KC_TRNS, KC_NUBS, KC_QUOT, KC_LCBR, KC_LPRN, KC_LBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_PAST, KC_GRV,  KC_EQL,  KC_MINS, KC_UNDS, KC_TRNS,
			KC_TRNS, KC_CIRC, KC_AMPR, KC_RCBR, KC_RPRN, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_TRNS,
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_ortho_5x15(
			KC_TRNS, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F11,  KC_SLEP, KC_F12,  KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_PSCR,
			KC_INS,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_NO,   KC_BRID, KC_BTN2, KC_BRIU, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_DEL,
			KC_TRNS, KC_F5,   KC_F6,   KC_F7,   KC_F8,   TG(1),   KC_INS,  KC_BTN1, KC_WH_U, KC_NO,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_TRNS, 
			KC_TRNS, KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_NO,   KC_DEL,  KC_MS_U, KC_WH_D, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_TRNS, 
			KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_PGUP, KC_END)
};

const rgblight_segment_t PROGMEM layer_caps[] = RGBLIGHT_LAYER_SEGMENTS(
  {0, 1, HSV_RED}
);

const rgblight_segment_t PROGMEM layer_qwerty[] = RGBLIGHT_LAYER_SEGMENTS(
  {5, 1, HSV_GOLD}
);

const rgblight_segment_t PROGMEM layer_game[] = RGBLIGHT_LAYER_SEGMENTS(
  {5, 1, HSV_RED}
);

const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    layer_qwerty,
    layer_game,
    layer_caps
);

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
}

bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(2, led_state.caps_lock);
    return true;
}

layer_state_t layer_state_set_user(layer_state_t state) {
    //rgblight_set_layer_state(0, layer_state_cmp(state, 1));
    rgblight_set_layer_state(1, layer_state_cmp(state, 1));
    return state;
}
